# Generated by Django 5.2.5 on 2025-08-21 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_host_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='snapshot_time',
            new_name='received_at',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
